### PR TITLE
[239] Ensure sub-resources are also proxied.

### LINKED ISSUE #239: Using restclient builder, exceptions are not mapped when calling subresources methods
Im using restclient builder to access jax-rs subresrources. However, when an error http response is received, instead of  calling a registered ResponseExceptionMapper, a ExceptionMapping.HandlerException is thrown with the message 'Handled internally'. To get the correct runtime exception thrown, i have to surround my call in try/catch and call the mapping manually:

```java
        try {
            return subResourceController.subresourceMethod(subresourceMethodParam);
        } catch (ExceptionMapping.HandlerException e) {
            // Mapping not performed on subresources :/
            try {
                Method subresourceMethod = SubResourceController.class.getMethod("subresourceMethod", SubresourceMethodParam.class);
                e.mapException(subresourceMethod); 
            } catch (RuntimeException e2) {
                throw e2; // rethrows the mapped exception
            } catch (Exception e3) {
                throw new AssertionError("Should not reach this", e3); // error during mapping
            }
            throw new AssertionError("Should not reach this", e); // exception not mapped
        }
```
With this construct, my ResponseExceptionMapper is called as expected, and I can access the desired fields (response status, body, ...)

Im using resteasy-client 6.2.4.Final and microprofile-rest-client 2.1.4.Final.

The exception is created there: https://github.com/resteasy/resteasy-microprofile/blob/main/rest-client-base/src/main/java/org/jboss/resteasy/microprofile/client/ExceptionMapping.java#L50

The stacktrace leading to it is:

```
org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException: Handled Internally
	at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:113)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:667)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:428)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:134)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:61)
```

For a call on a normal resource (not a subresource), the HandlerException is created, from the same call stack; but later mapped and rethrown as a WebApplicationException:

```
at be.fiscalteam.nitro.it.client.util.ClientExceptionMapper.toThrowable(ClientExceptionMapper.java:17)
	at be.fiscalteam.nitro.it.client.util.ClientExceptionMapper.toThrowable(ClientExceptionMapper.java:9)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:60)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:147)
```

This is the ` be.fiscalteam.nitro.it.client.util.ClientExceptionMapper.` registered using ` RestClientBuilder.newBuilder().register(new ClientExceptionMapper())`:

```java
public class ClientExceptionMapper implements ResponseExceptionMapper<WebApplicationException> {
    @Override
    public boolean handles(int status, MultivaluedMap<String, Object> headers) {
        return ResponseExceptionMapper.super.handles(status, headers);
    }

    @Override
    public WebApplicationException toThrowable(Response response) {
        return new WebApplicationException(response);
    }
}
```

The subresources I use are defined as simple Jax-rs interfaces, like for the normal resources but lacking a @Path annotation on the class.
Examples:

```java

@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public interface WsNitroRuleActionsSubResourceController  {

    @POST
    @Path("")
    WsNitroRuleAction createNitroRuleAction(@NotNull WsNitroRuleAction wsNitroRuleAction);

    @GET
    @Path("/list")
    List<WsNitroRuleAction> listNitroRuleActions();
}

@Path("nitroRule")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public interface WsNitroRuleController  {

    @POST
    @Path("")
    WsNitroRule createNitroRule(@NotNull WsNitroRule wsNitroRule);

    @GET
    @Path("/{id: [0-9]+}")
    WsNitroRule getNitroRule(@PathParam("id") Long id);

    @Path("/{id: [0-9]+}/actions")
    WsNitroRuleActionsSubResourceController getActionsSubresource(@PathParam("id") Long id);

}
```

### PR DESCRIPTION
**Pull request by jamezp**
resolves #239

### CODE REVIEW

**Comment by cghislai** [comment]
Thank you!
The only concern I have is with the close method. 
It will close the client, so the parent resource instance could not be used anymore afterwards. 
I think it would be more intuitive if the subresource was not closable, or that closing it would not have impact on the parent resource lifecycle.

If it is closable, I would expect something like that to work:

```
try (RootResource root = builder.build(Root.class)) {
  try (SubResource sub1 = root.getSubResource1() {
   //..
  }
  try (SubResource sub2 = root.getSubResource2() {
   //..
  }
}
```

**Comment by jamezp** [comment]
> Thank you! The only concern I have is with the close method. It will close the client, so the parent resource instance could not be used anymore afterwards. I think it would be more intuitive if the subresource was not closable, or that closing it would not have impact on the parent resource lifecycle.
> 
> If it is closable, I would expect something like that to work:
> 
> ```
> try (RootResource root = builder.build(Root.class)) {
>   try (SubResource sub1 = root.getSubResource1() {
>    //..
>   }
>   try (SubResource sub2 = root.getSubResource2() {
>    //..
>   }
> }
> ```

That's a good point. I did it mainly because https://download.eclipse.org/microprofile/microprofile-rest-client-3.0/microprofile-rest-client-spec-3.0.html#lifecycle indicates a client must implement `Closeable`, but I guess a sub-resource is different than a client. I'll undo that part as I agree with you.

I'll also remove the `RestClientProxy` interface too. I'll add some more tests around closing too.

**Comment by cghislai** [comment]
lgtm, thank you!

**Comment by jamezp** [comment]
@cghislai Thank you so much for your help on this. I'll get a release out by next week.

**Pull request merged**
